### PR TITLE
Removed eventListener on component unmount

### PR DESCRIPTION
**Pull request by rgabs**

### CODE REVIEW

**Comment by marudy** [comment]
Heads up! If you merge PR #10, you need to rename the event removed here, before proceeding with merge!

**Comment by marudy** [comment]
Hey @rgabs and thanks for the PR. I would like to merge it, but can you first change the event name from the deprecated to the new one? Because we also merged [this PR](https://github.com/rauchy/react-native-offline-mode/pull/10)? that changes the event name.

**Comment by rgabs** [comment]
Hey @marudy
I have made the required changes. 

> Now use the force to merge the PR,  you must. ⚡️🌟

**Review by marudy — APPROVED** [review]
Looks great, thanks!

**Comment by marudy** [comment]
@rgabs force is my friend hehe ⚔️

**Pull request merged**
