### PR TITLE
Replaced Deprecated Methods

### PR DESCRIPTION
**Pull request by AbhishekBiswal**

### CODE REVIEW

**Comment by rauchy** [comment]
Thanks for the patch!

Could you provide some description and references to what this actually solves?

I believe that these changes will break for most users unless you add dependency restrictions (on react or react-native I suppose)

**Comment by AbhishekBiswal** [comment]
@rauchy The current version of the module throws warnings (multiple, annoying) after upgrading (or using version >=) to React Native `0.48.0`. To notify users who are using the older RN version, you can mention the exact version of the module to be used in the README. 💯

**Comment by marudy** [comment]
Hi @AbhishekBiswal,

and thanks for your PR. It's time to merge it but before we do so, can you also change `reach` to `type` for the argument of `connect` function? That should be consistent as well.

If you don't have the time, just say it and I will do it for you.

Thanks mate,
Tasos

**Comment by AbhishekBiswal** [comment]
Hey @marudy Done, can you check and merge? Thanks!

**Review by marudy — APPROVED** [review]
Looks good @AbhishekBiswal, will merge now :)

Thanks again for the PR, mate.

**Pull request merged**
